### PR TITLE
Issue 12

### PR DESCRIPTION
**Pull request by NiklausHofer**
This is a Fix for Issue #12 

Until now: If the Message Body was not HTML encoded but contained special characters (such as &), the HTML decoder failed and in turn the OTR Module failed. To the user, an ugly blob (the encrypted message) was displayed.

Now: The HTML decoder's exception is caught. The user is presented with the raw decrypted message.

Also: The body of the message gets no longer HTML escaped. The xhtml part of the Stanza is of course still HTML encoded. That ought to be enough. Receiving HTML tags in the body is VERY annoying on CLI clients. This is a separate commit (c1c227b), if you don't like it, you can always cherry-pick 69b3bb6.

### CODE REVIEW

**Comment by NiklausHofer** [comment]
Had a chance to test it against Pidgin. Works fine.

**Comment by afflux** [comment]
Thanks for your effort. Unfortunately, I have to reject this PR for the following reasons:

#### Re: Outgoing messages with escaped the HTML part and unescaped body part
>For example, suppose there's a Jabber message sent [...], where
the body section contains an encryption of "to put something in bold,
wrap <b></b> around it" and the xhtml section contains an encryption of
"to put something in bold, wrap &lt;b&gt;&lt;/b&gt; around it".  Then an
adversary replaces the OTR block in the xhtml section with the one from
the body section.  An end user with an xhtml-aware client will see "to
put something in bold, wrap  around it", and the attacker has
successfully modified the message.

[Ian Goldberg, May 2008](https://lists.cypherpunks.ca/pipermail/otr-dev/2008-May/000777.html)

#### Re: Falling back to non-HTML-decoding
Assume a user has an OTR client that sends OTR messages without HTML-escaping before. With your proposed patch, the following behaviour occurs:

1. sending user sends &something; - receiving user sees &something;
2. sending user sends & - receiving user sees &
3. sending user sends &amp; - receiving user sees &

**Comment by NiklausHofer** [comment]
> sending user sends &something; - receiving user sees &something;
Not sure if I understand exactly what you mean. But that should not happen. With my patch, an attempt to strip the HTML Tags is made first. Only if that fails, the user is displayed with the raw message. So the behaviour would be something like this:

 * Sender sends &amp;, receiver sees &
 * Sender sends &, receiver sees &
 * Sender sends &amp;amp;, receiver sees &amp;

Weird shit only happens here:

* Sender sends &amp;&, receiver sees &amp;&

But that would be one strange message anyway

**Comment by NiklausHofer** [comment]
> sending user sends &amp;amp; - receiving user sees & [not okay]

But that what happens right now, without my patch, anyway.

**Comment by afflux** [comment]
True. 

A thought: does it make sense to apply the stripping only if the body and html ciphertext parts were the same?
If they differed or there was no HTML part, we could assume that the body part was in fact text/plain.
If they were the same and the stripping fails, we could log a message in the visible chat history (e.g., "The following message could not be parsed correctly and may appear deformed")?

**Comment by NiklausHofer** [comment]
94850d9 : Body is escaped if the Stanza has an xhtml element (same as before). If the Stanza has no HTML element, the message is not escaped (new).

If I understand Goldberg's concern correctly, this behaviour should be save, since there is no xhtml section the attacker could replace the content of.

Not sure if that's good enough though: Could the attacker possibly just manually add an xhtml section? Is that a thing? Because then, the attack would still work.

**Comment by NiklausHofer** [comment]
> A thought: does it make sense to apply the stripping only if the body and html ciphertext parts were the same?

I like the part about not stripping the body if there was no xhtml element in the first place.

**Comment by afflux** [comment]
> 94850d9

Side note: that commit does not appear to show up in this PR for some reason.

> Not sure if that's good enough though: Could the attacker possibly just manually add an xhtml section? Is that a thing? Because then, the attack would still work.

I think so.

> I like the part about not stripping the body if there was no xhtml element in the first place.

Unfortunately, I won't find the time to work on this, though I'd be happy to accept a pull request. :-)

**Comment by NiklausHofer** [comment]
> A thought: does it make sense to apply the stripping only if the body and html ciphertext parts were the same?

I tried that quickly, but found a problem: Pidgin does not appear to put an xhtml/html part into the Stanza it sends. Not even if I send messages with formatted text (special fonts, parts of the text bold). There is always only the body tag :( I guess it makes sense, since it would put the same thing in both places anyway, it saves space by doing like that.

**Comment by NiklausHofer** [comment]
Undone all changes to the way outgoing messages are handled.

**Pull request closed without merging**
